fun main(args: Array<String>) {
    val graph = Graph.createUnidirectionalUnweightedGraph("nodes0.txt", "edges0.txt")
    println(graph.toString())
    graph.bfs(0, 2)
    graph.bfs(2, 0)
    graph.bfs(4, 1)
    graph.bfs(1, 3)
    graph.ucs(0, 2)
    graph.ucs(2, 0)
    graph.ucs(4, 1)
    graph.ucs(1, 3)
    graph.id(0, 2)
    graph.id(2, 0)
    graph.id(4, 1)
    graph.id(1, 3)
}