fun main(args: Array<String>) {
    val graph1 = Graph.createUnidirectionalUnweightedGraph("nodes0.txt", "edges0.txt")
    println(graph1.toString())
    graph1.bfs(0, 2)
    graph1.bfs(2, 0)
    graph1.bfs(4, 1)
    graph1.bfs(1, 3)
    graph1.ucs(0, 2)
    graph1.ucs(2, 0)
    graph1.ucs(4, 1)
    graph1.ucs(1, 3)
    graph1.id(0, 2)
    graph1.id(2, 0)
    graph1.id(4, 1)
    graph1.id(1, 3)

    val graph2 = Graph.createBidirectionalWeightedGraph("nodes1.txt", "edges1.txt")
    graph2.bfs(0, 9)
    graph2.astar(0, 9)
}